/**
 * PENNUENG GAME - Most Played All-Time Retro Legends Database
 * Systems: NES, SNES, GBA, GBC, Neo Geo/Arcade, Sega Genesis, N64, PS1, and MS-DOS
 * 100% 1:1 Verified Exact Stream Matches & Official Box Arts
 */

const RETRO_GAMES_DATABASE = [
  {
    "id": "ps1-road-rash",
    "title": "Road Rash (PS1)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Racing",
    "year": 1995,
    "developer": "Electronic Arts",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Road%20Rash%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "ภาคคลาสสิกร็อค 90s มอเตอร์ไซค์เตะต่อย ฟาดกระบอง เพลง Soundgarden",
    "controls": "ลูกศร: เลี้ยว | Z: คันเร่ง (X) | X: เบรก (Square) | A: ต่อย/ถีบ | S: ฟาดกระบอง",
    "embedUrl": "https://www.retrogames.cc/embed/41506-road-rash.html"
  },
  {
    "id": "ps1-road-rash-3d",
    "title": "Road Rash 3D (PS1)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Racing",
    "year": 1998,
    "developer": "Electronic Arts",
    "rating": 4.9,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Road%20Rash%203D%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "สิงห์มอเตอร์ไซค์ 3D บิดปะทะแก๊งซิ่งคู่แข่ง ชกต่อยกลางถนน",
    "controls": "ลูกศร: เลี้ยว | Z: คันเร่ง | X: เบรก | A/S: ชก/หวดอาวุธ ซ้าย-ขวา",
    "embedUrl": "https://www.retrogames.cc/embed/41508-road-rash-3d.html"
  },
  {
    "id": "ps1-pepsiman",
    "title": "Pepsiman (1999)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1999,
    "developer": "KID",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Pepsiman%20(Japan).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เป๊ปซี่แมนฮีโร่วิ่งส่งเป๊ปซี่ระดับตำนาน หลบสิ่งกีดขวางและกระป๋องยักษ์ไล่หลัง",
    "controls": "ลูกศร: ซ้าย/ขวา | Z: สไลด์ (X) | X: กระโดด (Square) | A: พุ่งชน (Circle) | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/42754-pepsiman-japan.html"
  },
  {
    "id": "ps1-harvest-moon-btn",
    "title": "Harvest Moon: Back to Nature",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "RPG",
    "year": 1999,
    "developer": "Victor Interactive",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Harvest%20Moon%20-%20Back%20to%20Nature%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    "description": "เกมปลูกผัก เลี้ยงวัว จีบสาว ที่ครองใจเกมเมอร์ไทยมากที่สุดตลอดกาล",
    "controls": "ลูกศร: เดิน | Z: หยิบ/คุย (X) | X: ใช้อุปกรณ์ (Square) | A: กิน/เก็บ (Triangle) | S: วิ่ง (R1)",
    "embedUrl": "https://www.retrogames.cc/embed/40055-harvest-moon-back-to-nature.html"
  },
  {
    "id": "ps1-tekken-3",
    "title": "Tekken 3 (1998)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Fighting",
    "year": 1998,
    "developer": "Namco",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Tekken%203%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "สุดยอดเกมต่อสู้ 3D ในตำนาน หมัดเหล็ก Jin Kazama, Hwoarang, Eddy Gordo",
    "controls": "ลูกศร: เคลื่อนที่ | A: ต่อยซ้าย | S: ต่อยขวา | Z: เตะซ้าย | X: เตะขวา | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/40238-tekken-3.html"
  },
  {
    "id": "ps1-crash-team-racing",
    "title": "Crash Team Racing (CTR)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Racing",
    "year": 1999,
    "developer": "Naughty Dog",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/CTR%20-%20Crash%20Team%20Racing%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "ศึกแข่งรถโกคาร์ทดริฟท์พ่นไฟและยิงอาวุธสุดมันส์ของเจ้าหมา Crash Bandicoot",
    "controls": "ลูกศร: เลี้ยว | Z: เร่งความเร็ว (X) | X: ยิงอาวุธ (Circle) | A/S: กระโดดดริฟท์ (L1/R1)",
    "embedUrl": "https://www.retrogames.cc/embed/41687-crash-team-racing.html"
  },
  {
    "id": "ps1-bloody-roar-2",
    "title": "Bloody Roar II (แปลงร่างสัตว์)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Fighting",
    "year": 1999,
    "developer": "Eighting / Hudson",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Bloody%20Roar%20II%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "ศึกต่อสู้แปลงร่างเป็นสัตว์ดุร้าย เสือโคร่ง หมาป่า ตุ่น สิงโต พร้อมท่าไม้ตายสัตว์ป่าสุดโหด",
    "controls": "ลูกศร: ทิศทาง | A: ต่อย | Z: เตะ | X: ปุ่มแปลงร่างสัตว์ (Beast)",
    "embedUrl": "https://www.retrogames.cc/embed/41623-bloody-roar-2-bringer-of-new-age.html"
  },
  {
    "id": "ps1-jackie-chan",
    "title": "Jackie Chan Stuntmaster (เฉินหลง)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 2000,
    "developer": "Radical Entertainment",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Jackie%20Chan%20Stuntmaster%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เกมแอ็กชันผจญภัยสุดฮาของเฉินหลง บู๊แหลก เตะต่อย ใช้เก้าอี้และไม้ถูพื้นปราบเหล่าร้าย",
    "controls": "ลูกศร: เคลื่อนที่ | Z: ต่อย (Square) | X: เตะ (X) | A: กระโดด (Circle) | S: กลิ้งตัว",
    "embedUrl": "https://www.retrogames.cc/embed/41909-jackie-chan-stuntmaster.html"
  },
  {
    "id": "ps1-dragon-ball-gt",
    "title": "Dragon Ball GT: Final Bout",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Fighting",
    "year": 1997,
    "developer": "Bandai",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Dragon%20Ball%20GT%20-%20Final%20Bout%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "ศึกประลองพลังคลื่นเต่า ปล่อยพลังลำแสงซูเปอร์ไซย่า 4 โกคู เบจิต้า และเบบี้",
    "controls": "ลูกศร: บังคับทิศทาง/บิน | A: ต่อย | S: เตะ | Z: ยิงพลังคิ | X: ชาร์จพลัง",
    "embedUrl": "https://www.retrogames.cc/embed/40092-dragon-ball-gt-final-bout.html"
  },
  {
    "id": "ps1-yugioh",
    "title": "Yu-Gi-Oh! Forbidden Memories",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Strategy",
    "year": 1999,
    "developer": "Konami",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Yu-Gi-Oh!%20Forbidden%20Memories%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    "description": "เกมการ์ดยูกิโออียิปต์โบราณ ผสมการ์ดมังกรทองตาคู่และตามหาไอเทมพันปี",
    "controls": "ลูกศร: เลื่อนการ์ด | Z: วางการ์ด (X) | X: ผสมการ์ด (Square) | A: ดูรายละเอียด",
    "embedUrl": "https://www.retrogames.cc/embed/40173-yu-gi-oh-forbidden-memories.html"
  },
  {
    "id": "ps1-silent-hill",
    "title": "Silent Hill (1999)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1999,
    "developer": "Konami",
    "rating": 5.0,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Silent%20Hill%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    "description": "เมืองสายหมอกหลอนในมิติสนิม ตามหาลูกสาวท่ามกลางเสียงวิทยุเตือนปีศาจ",
    "controls": "ลูกศร: เดิน | Z: ยิง/สำรวจ (X) | X: วิ่ง (Square) | A: ยกปืนเล็ง (R1)",
    "embedUrl": "https://www.retrogames.cc/embed/41684-silent-hill.html"
  },
  {
    "id": "ps1-resident-evil-2",
    "title": "Resident Evil 2 (Leon)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1998,
    "developer": "Capcom",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Resident%20Evil%202%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    "description": "หนีตายจากฝูงซอมบี้ในสถานีตำรวจเมืองแรคคูนซิตีกับ Leon S. Kennedy",
    "controls": "ลูกศร: หมุน/เดินหน้า | Z: ยิง/สำรวจ (X) | X: ยกเลิก/วิ่ง (Square) | A: ยกปืนเล็ง (R1)",
    "embedUrl": "https://www.retrogames.cc/embed/42943-resident-evil-2-dual-shock-ver-disc-1-leon.html"
  },
  {
    "id": "ps1-wwf-smackdown-2",
    "title": "WWF SmackDown! 2: Know Your Role",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Fighting",
    "year": 2000,
    "developer": "Yuke's",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/WWF%20SmackDown!%202%20-%20Know%20Your%20Role%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "เกมมวยปล้ำยุคทอง The Rock, Stone Cold, Triple H, Undertaker โดดทับโต๊ะและเก้าอี้สุดมันส์",
    "controls": "ลูกศร: เคลื่อนที่ | Z: ต่อย (Square) | X: จับล็อก (Circle) | A: วิ่ง (Triangle) | S: ขึ้นเชือก",
    "embedUrl": "https://www.retrogames.cc/embed/42195-wwf-smackdown-2.html"
  },
  {
    "id": "ps1-twisted-metal-2",
    "title": "Twisted Metal 2 (รถยิงปืน)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1996,
    "developer": "SingleTrac",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Twisted%20Metal%202%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "สงครามรถแต่งยิงมิสไซล์ระเบิดเมือง Sweet Tooth, Minion, Axel ถล่มหอไอเฟล",
    "controls": "ลูกศร: เลี้ยว | Z: คันเร่ง | X: เบรก | A: ยิงปืนกล | S: ยิงมิสไซล์",
    "embedUrl": "https://www.retrogames.cc/embed/41546-twisted-metal-2.html"
  },
  {
    "id": "ps1-crash-1",
    "title": "Crash Bandicoot 1",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Platformer",
    "year": 1996,
    "developer": "Naughty Dog",
    "rating": 4.9,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Crash%20Bandicoot%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เจ้าหมาแครชหมุนตัวสปิน กระโดดข้ามสะพานไม้ลอยฟ้า และวิ่งหนีหินกลิ้งยักษ์ไล่หลัง",
    "controls": "ลูกศร: เดิน | Z: กระโดด (X) | X: สปินหมุนตัว (Square)",
    "embedUrl": "https://www.retrogames.cc/embed/40784-crash-bandicoot.html"
  },
  {
    "id": "ps1-chocobo-racing",
    "title": "Chocobo Racing (แข่งรถโจโคโบะ)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Racing",
    "year": 1999,
    "developer": "Squaresoft",
    "rating": 4.9,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Chocobo%20Racing%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "แข่งรถแฟนตาซี ดริฟท์เก็บลูกแก้วเวทมนตร์ ปล่อยคาถาไฟ สายฟ้า และบาฮามุท",
    "controls": "ลูกศร: เลี้ยว | Z: เร่งความเร็ว | X: ใช้เวทมนตร์ | A: สกิลประจำตัว",
    "embedUrl": "https://www.retrogames.cc/embed/41660-chocobo-racing.html"
  },
  {
    "id": "ps1-digimon-world",
    "title": "Digimon World (เลี้ยงดิจิมอน)",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "RPG",
    "year": 1999,
    "developer": "Bandai",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Digimon%20World%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    "description": "พาคู่หูดิจิมอนฝึกฝน ให้อาหาร พาเข้าห้องน้ำ พัฒนาร่าง และฟื้นฟูเกาะ File Island",
    "controls": "ลูกศร: เดิน | Z: สำรวจ/คุย | X: ยกเลิก | A: เมนูคำสั่ง",
    "embedUrl": "https://www.retrogames.cc/embed/41731-digimon-world.html"
  },
  {
    "id": "ps1-castlevania-sotn",
    "title": "Castlevania: Symphony of the Night",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1997,
    "developer": "Konami",
    "rating": 5.0,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Castlevania%20-%20Symphony%20of%20the%20Night%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    "description": "มาสเตอร์พีซแห่งปราสาทแดร็กคูล่า Alucard บุกปราสาทกลับหัว ระบบ RPG สมบูรณ์แบบ",
    "controls": "ลูกศร: เดิน | Z: ฟันดาบ (Square) | X: กระโดด (X) | A: แปลงร่างค้างคาว/หมอก",
    "embedUrl": "https://www.retrogames.cc/embed/41504-castlevania-symphony-of-the-night.html"
  },
  {
    "id": "ps1-metal-gear-solid",
    "title": "Metal Gear Solid",
    "platform": "ps1",
    "platformName": "PlayStation 1",
    "genre": "Action",
    "year": 1998,
    "developer": "Konami",
    "rating": 5.0,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Metal%20Gear%20Solid%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    "description": "สุดยอดเกมสายลับ Solid Snake ลอบเร้นฐานเกาะ Shadow Moses",
    "controls": "ลูกศร: ย่อง/หมอบ | Z: ต่อย/ยิง | X: หมอบคลาน | A: เรียกวิทยุ Codec",
    "embedUrl": "https://www.retrogames.cc/embed/43266-metal-gear-solid-disc-1.html"
  },
  {
    "id": "snes-donkey-kong-country",
    "title": "Donkey Kong Country",
    "platform": "snes",
    "platformName": "Super Nintendo",
    "genre": "Platformer",
    "year": 1994,
    "developer": "Rare / Nintendo",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Donkey%20Kong%20Country%20(USA)%20(Rev%201).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "ลิงดองกี้คองและดิดดี้คอง กราฟิกเรนเดอร์ 3D สุดล้ำและเพลงประกอบระดับตำนาน",
    "controls": "ลูกศร: เดิน | Z: กระโดด | X: กลิ้งตัว/ขว้างกล้วย | A: สลับตัวละคร",
    "embedUrl": "https://www.retrogames.cc/embed/23005-donkey-kong-country-usa.html"
  },
  {
    "id": "snes-donkey-kong-2",
    "title": "Donkey Kong Country 2",
    "platform": "snes",
    "platformName": "Super Nintendo",
    "genre": "Platformer",
    "year": 1995,
    "developer": "Rare / Nintendo",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Donkey%20Kong%20Country%202%20-%20Diddy's%20Kong%20Quest%20(USA)%20(En%2CFr).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "ดิดดี้คองและดิกซี่คองผมเปียเหินฟ้า บุกเรือโจรสลัดจระเข้ช่วยดองกี้คอง",
    "controls": "ลูกศร: เดิน | Z: กระโดด | X: หมุนผมลอยตัว/กลิ้ง | A: อุ้มเพื่อน",
    "embedUrl": "https://www.retrogames.cc/embed/23926-donkey-kong-country-2-diddy-s-kong-quest-usa-en-fr.html"
  },
  {
    "id": "snes-chrono-trigger",
    "title": "Chrono Trigger (1995)",
    "platform": "snes",
    "platformName": "Super Nintendo",
    "genre": "RPG",
    "year": 1995,
    "developer": "Squaresoft",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Chrono%20Trigger%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    "description": "สุดยอด RPG ท่องมิติกาลเวลา จากการรวมตัวของบิดา Final Fantasy และผู้เขียน Dragon Ball",
    "controls": "ลูกศร: เดิน | Z: สำรวจ/โจมตี | X: ยกเลิก/วิ่ง | A: เมนูท่าไม้ตายคู่",
    "embedUrl": "https://www.retrogames.cc/embed/22857-chrono-trigger-usa.html"
  },
  {
    "id": "snes-top-gear",
    "title": "Top Gear (1992)",
    "platform": "snes",
    "platformName": "Super Nintendo",
    "genre": "Racing",
    "year": 1992,
    "developer": "Gremlin Graphics",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Top%20Gear%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    "description": "เกมแข่งรถไนตรัสพ่นไฟระดับตำนานร้านเกม พร้อมเพลงซาวด์แทร็กกระหึ่มยุค 90s",
    "controls": "ลูกศร: เลี้ยว | Z: คันเร่ง (B) | X: ไนตรัส Nitro (Y) | A: เบรก (A)",
    "embedUrl": "https://www.retrogames.cc/embed/23881-top-gear-usa.html"
  },
  {
    "id": "snes-sunset-riders",
    "title": "Sunset Riders (คาวบอย 4 คน)",
    "platform": "snes",
    "platformName": "Super Nintendo",
    "genre": "Shooter",
    "year": 1993,
    "developer": "Konami",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Sunset%20Riders%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    "description": "นักล่าค่าหัวคาวบอย บุกดงโจร ขี่ม้าไล่ยิง ปืนลูกซอง ปืนพกคู่ และปืนไฟ",
    "controls": "ลูกศร: ทิศทาง/สไลด์ | Z: ยิงปืน | X: กระโดด",
    "embedUrl": "https://www.retrogames.cc/embed/19970-sunset-riders-usa.html"
  },
  {
    "id": "nes-contra",
    "title": "Contra (1988)",
    "platform": "nes",
    "platformName": "NES / Famicom",
    "genre": "Shooter",
    "year": 1988,
    "developer": "Konami",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Contra%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    "description": "เกมยิงบู๊ล้างผลาญระดับตำนาน พร้อมสูตร 30 ตัว บน บน ล่าง ล่าง ซ้าย ขวา ซ้าย ขวา B A",
    "controls": "ลูกศร: เล็ง/เดิน | Z: ปุ่ม B (ยิง) | X: ปุ่ม A (กระโดด) | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/16841-contra-usa.html"
  },
  {
    "id": "nes-circus-charlie",
    "title": "Circus Charlie (ละครสัตว์)",
    "platform": "nes",
    "platformName": "NES / Famicom",
    "genre": "Arcade",
    "year": 1986,
    "developer": "Konami",
    "rating": 4.8,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Circus%20Charlie%20(Japan).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เกมละครสัตว์ในตำนาน ขี่สิงโตรอดบ่วงไฟ ไต่เชือก เหยียบลูกบอล และโหนบาร์",
    "controls": "ลูกศร: หน้า/หลัง | Z / X: กระโดดข้ามสิ่งกีดขวาง",
    "embedUrl": "https://www.retrogames.cc/embed/21342-circus-charlie-japan.html"
  },
  {
    "id": "nes-adventure-island",
    "title": "Adventure Island (เกาะผจญภัย)",
    "platform": "nes",
    "platformName": "NES / Famicom",
    "genre": "Platformer",
    "year": 1986,
    "developer": "Hudson Soft",
    "rating": 4.8,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Hudson's%20Adventure%20Island%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "นายทากาฮาชิขี่สเก็ตบอร์ด ปาขวานหิน กินผลไม้เพิ่มพลังช่วยแฟนสาว",
    "controls": "ลูกศร: วิ่ง | Z: ปาขวาน | X: กระโดด | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/20528-hudson-s-adventure-island-usa.html"
  },
  {
    "id": "nes-battle-city",
    "title": "Battle City (รถถัง)",
    "platform": "nes",
    "platformName": "NES / Famicom",
    "genre": "Arcade",
    "year": 1985,
    "developer": "Namco",
    "rating": 4.8,
    "featured": false,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9t.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    "description": "ขับรถถังปกป้องฐานนกอินทรี และทำลายรถถังศัตรูให้หมดสิ้น",
    "controls": "ลูกศร: บังคับทิศทาง | Z / X: ยิงกระสุนปืนใหญ่",
    "embedUrl": "https://www.retrogames.cc/embed/16882-battle-city-japan.html"
  },
  {
    "id": "nes-megaman-2",
    "title": "Mega Man 2 (Rockman 2)",
    "platform": "nes",
    "platformName": "NES / Famicom",
    "genre": "Action",
    "year": 1988,
    "developer": "Capcom",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Mega%20Man%202%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f41.jpg",
    "description": "ภาคที่ได้รับการยกย่องว่าดีที่สุดของร็อคแมน กำจัด 8 บอสเพื่อชิงอาวุธ",
    "controls": "ลูกศร: เดิน | Z: ยิงบัสเตอร์ | X: กระโดด | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/20460-mega-man-2-usa.html"
  },
  {
    "id": "gba-pokemon-firered",
    "title": "Pokemon FireRed Version",
    "platform": "gba",
    "platformName": "Game Boy Advance",
    "genre": "RPG",
    "year": 2004,
    "developer": "Game Freak",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance/master/Named_Boxarts/Pokemon%20-%20FireRed%20Version%20(USA%2C%20Europe).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f46.jpg",
    "description": "ผจญภัยในเขต Kanto เลือกโปเกมอนคู่หูตัวแรก Charmander, Squirtle, Bulbasaur และปราบแก๊งร็อคเก็ต",
    "controls": "ลูกศร: เดิน | Z: ตกลง (A) | X: ยกเลิก/วิ่ง (B) | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/45076-pokemon-fire-red-extended-v3-4-7.html"
  },
  {
    "id": "gbc-pokemon-crystal",
    "title": "Pokemon Crystal Version",
    "platform": "gbc",
    "platformName": "Game Boy Color",
    "genre": "RPG",
    "year": 2000,
    "developer": "Game Freak",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy_Color/master/Named_Boxarts/Pokemon%20-%20Crystal%20Version%20(USA%2C%20Europe)%20(Rev%20A).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f46.jpg",
    "description": "ภาคคลาสสิกที่ดีที่สุดของ Game Boy Color ผจญภัยดินแดน Johto ปะทะ Suicune",
    "controls": "ลูกศร: เดิน | Z: ปุ่ม A (ตกลง) | X: ปุ่ม B (ยกเลิก) | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/44705-pokemon-perfect-crystal-2020-update.html"
  },
  {
    "id": "gbc-pokemon-crystal-clear",
    "title": "Pokemon Crystal Clear",
    "platform": "gbc",
    "platformName": "Game Boy Color",
    "genre": "RPG",
    "year": 2020,
    "developer": "ShockSlayer",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy_Color/master/Named_Boxarts/Pokemon%20-%20Crystal%20Version%20(USA%2C%20Europe)%20(Rev%20A).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f46.jpg",
    "description": "เวอร์ชัน Open-World เลือกเกิดได้ 24 จุด เลือกโปเกมอนคู่หูได้ทุกตัว ท่องได้ทั้ง Johto และ Kanto",
    "controls": "ลูกศร: เดิน | Z: ตกลง | X: ยกเลิก/วิ่ง | Enter: Start",
    "embedUrl": "https://www.retrogames.cc/embed/46954-pokemon-crystal-clear-standard-v2-5-10.html"
  },
  {
    "id": "arcade-metal-slug",
    "title": "Metal Slug (Neo Geo)",
    "platform": "arcade",
    "platformName": "Neo Geo / Arcade",
    "genre": "Action",
    "year": 1996,
    "developer": "Nazca / SNK",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/SNK_-_Neo_Geo/master/Named_Boxarts/Metal%20Slug%20-%20Super%20Vehicle-001.png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "ทหารจิ๋วลุยแหลก ขับรถถัง ยิงปืนกลหนัก Heavy Machine Gun และปาระเบิด",
    "controls": "ลูกศร: เดิน | Z: ยิง | X: กระโดด | C: ปาระเบิด | Space: หยอดเหรียญ",
    "embedUrl": "https://www.retrogames.cc/embed/9157-metal-slug-super-vehicle-001.html"
  },
  {
    "id": "arcade-metal-slug-x",
    "title": "Metal Slug X (Neo Geo)",
    "platform": "arcade",
    "platformName": "Neo Geo / Arcade",
    "genre": "Action",
    "year": 1999,
    "developer": "SNK",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/SNK_-_Neo_Geo/master/Named_Boxarts/Metal%20Slug%20X%20-%20Super%20Vehicle-001%20(NGM-2500%2C%20NGH-2500).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "ภาคอัปเกรดสุดมันส์ ปืนเลเซอร์ อูฐปืนกล และเอเลี่ยนยานบิน",
    "controls": "ลูกศร: เดิน | Z: ยิง | X: กระโดด | C: ปาระเบิด | Space: หยอดเหรียญ",
    "embedUrl": "https://www.retrogames.cc/embed/9170-metal-slug-x-super-vehicle-001-ngm-2500-ngh-2500.html"
  },
  {
    "id": "arcade-cadillacs-dinosaurs",
    "title": "Cadillacs and Dinosaurs (มุสตาฟา)",
    "platform": "arcade",
    "platformName": "Neo Geo / Arcade",
    "genre": "Action",
    "year": 1993,
    "developer": "Capcom",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9m.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เกมตู้หยอดเหรียญลุยแหลกยุค 90s มุสตาฟาเตะตัดขา ยิงปืนกล ปราบไดโนเสาร์คลั่ง",
    "controls": "ลูกศร: เดิน | Z: ต่อย/ใช้อาวุธ | X: กระโดด | Z+X: ท่าไม้ตายหมุนตัว | Space: หยอดเหรียญ (Coin)",
    "embedUrl": "https://www.retrogames.cc/embed/8043-cadillacs-and-dinosaurs-hack-930201-etc-hack.html"
  },
  {
    "id": "arcade-kof-98",
    "title": "The King of Fighters '98",
    "platform": "arcade",
    "platformName": "Neo Geo / Arcade",
    "genre": "Fighting",
    "year": 1998,
    "developer": "SNK",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9r.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "ราชาแห่งเกมต่อสู้แท็กทีม 3 vs 3 Kyo Kusanagi, Iori Yagami, Mai Shiranui",
    "controls": "ลูกศร: ทิศทาง | A: ต่อยเบา | S: เตะเบา | Z: ต่อยหนัก | X: เตะหนัก | Space: หยอดเหรียญ",
    "embedUrl": "https://www.retrogames.cc/embed/10368-the-king-of-fighters-98-the-slugfest-king-of-fighters-98-dream-match-never-ends-ngm-2420.html"
  },
  {
    "id": "sega-sonic-the-hedgehog-2",
    "title": "Sonic The Hedgehog 2",
    "platform": "sega",
    "platformName": "Sega Genesis",
    "genre": "Platformer",
    "year": 1992,
    "developer": "Sega",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20The%20Hedgehog%202%20(World).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f49.jpg",
    "description": "เจ้าเม่นสายฟ้าโซนิคและคู่หูเทลส์ วิ่งทะลุความเร็วเสียง Spin Dash ปราบ ดร.เอ้กแมน",
    "controls": "ลูกศร: ซ้าย/ขวา กลิ้ง/หมอบ | Z / X / C: กระโดด / Spin Dash",
    "embedUrl": "https://www.retrogames.cc/embed/18468-sonic-the-hedgehog-2-world.html"
  },
  {
    "id": "sega-streets-of-rage-2",
    "title": "Streets of Rage 2",
    "platform": "sega",
    "platformName": "Sega Genesis",
    "genre": "Action",
    "year": 1992,
    "developer": "Sega / Ancient",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Streets%20of%20Rage%202%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "สุดยอดเกมแอ็กชันเดินหน้าต่อยตีอันดับ 1 ของ Sega Axel, Blaze, Skate, Max เพลงซาวด์แทร็กกระหึ่ม",
    "controls": "ลูกศร: เดิน | Z: ต่อย/จับทุ่ม | X: กระโดด | A: ท่าไม้ตาย Grand Upper",
    "embedUrl": "https://www.retrogames.cc/embed/28481-streets-of-rage-2-usa.html"
  },
  {
    "id": "sega-golden-axe",
    "title": "Golden Axe (ขวานทอง)",
    "platform": "sega",
    "platformName": "Sega Genesis",
    "genre": "Action",
    "year": 1989,
    "developer": "Sega",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Golden%20Axe%20(World).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    "description": "ศึกนักรบขวานทอง คนแคระ และอเมซอน ขี่ไดโนเสาร์ ปล่อยมังกรไฟถล่ม Death Adder",
    "controls": "ลูกศร: เดิน | Z: โจมตี/ฟัน | X: กระโดด | A: ร่ายเวทมนตร์",
    "embedUrl": "https://www.retrogames.cc/embed/16712-golden-axe-world.html"
  },
  {
    "id": "sega-shinobi-3",
    "title": "Shinobi III: Return of the Ninja Master",
    "platform": "sega",
    "platformName": "Sega Genesis",
    "genre": "Action",
    "year": 1993,
    "developer": "Sega",
    "rating": 5.0,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Shinobi%20III%20-%20Return%20of%20the%20Ninja%20Master%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "สุดยอดเกมนินจา Joe Musashi ขี่ม้า โหนเชือก ปาดาวกระจายและวิชานินจา 4 ธาตุ",
    "controls": "ลูกศร: เดิน/หมอบ | Z: ปาดาวกระจาย/ฟันดาบ | X: กระโดด/ตีลังกา | A: วิชานินจา",
    "embedUrl": "https://www.retrogames.cc/embed/30503-shinobi-iii-return-of-the-ninja-master-usa.html"
  },
  {
    "id": "n64-super-smash-bros",
    "title": "Super Smash Bros. 64",
    "platform": "n64",
    "platformName": "Nintendo 64",
    "genre": "Fighting",
    "year": 1999,
    "developer": "HAL Laboratory / Nintendo",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_64/master/Named_Boxarts/Super%20Smash%20Bros.%20(USA).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    "description": "ต้นกำเนิดศึกประลองยุทธรวมดารา Nintendo 64 Mario, Donkey Kong, Link, Pikachu, Fox, Yoshi ซัดตกเวที",
    "controls": "ลูกศร: เคลื่อนที่ | Z: โจมตีปกติ (A) | X: ท่าไม้ตายพิเศษ (B) | A: กระโดด (C-Buttons) | S: ป้องกัน (Z-Trigger)",
    "embedUrl": "https://www.retrogames.cc/embed/32117-super-smash-bros-usa.html"
  },
  {
    "id": "dos-doom",
    "title": "DOOM (1993)",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Shooter",
    "year": 1993,
    "developer": "id Software",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r0o.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    "description": "เกมยิงมุมมองบุคคลที่หนึ่งระดับตำนาน บุกตะลุยฝูงปีศาจจากนรกบนดาวอังคาร",
    "controls": "ลูกศร: เดิน / หัน | Ctrl: ยิง | Alt: สไลด์ข้าง | Space: เปิดประตู | 1-7: เปลี่ยนอาวุธ",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fdoom.jsdos"
  },
  {
    "id": "dos-prince-of-persia",
    "title": "Prince of Persia (1989)",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Platformer",
    "year": 1989,
    "developer": "Brøderbund",
    "rating": 4.8,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Prince%20of%20Persia%20(1990).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4q.jpg",
    "description": "การผจญภัยของเจ้าชายเปอร์เซียในคุกใต้ดิน ต้องช่วยเจ้าหญิงให้ได้ภายใน 60 นาที",
    "controls": "ลูกศร ซ้าย-ขวา: วิ่ง | ลูกศร ขึ้น: กระโดด / ปีน | Shift: เดินย่อง / หยิบของ / ปัดดาบ",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fprince-of-persia.jsdos"
  },
  {
    "id": "dos-dangerous-dave",
    "title": "Dangerous Dave",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Platformer",
    "year": 1988,
    "developer": "John Romero",
    "rating": 4.7,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Dangerous%20Dave%20(1990).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "เกมเก็บถ้วยทองในตำนานห้องคอมโรงเรียน เก็บไอเทมและเจ็ทแพ็คเพื่อผ่านด่าน",
    "controls": "ลูกศร: ซ้าย / ขวา | Space / ลูกศรขึ้น: กระโดด | Ctrl: ยิงปืน",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fdave.jsdos"
  },
  {
    "id": "dos-duke-nukem-3d",
    "title": "Duke Nukem 3D (1996)",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Shooter",
    "year": 1996,
    "developer": "3D Realms",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Duke%20Nukem%203D%20(1996).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    "description": "ฮีโร่กล้ามโต Duke Nukem บุกกวาดล้างเอเลี่ยนที่มายึดครองลอสแองเจลิส",
    "controls": "ลูกศร / WASD: เคลื่อนที่ | Ctrl: ยิง | Space: เปิดประตู/สำรวจ | E: เตะ",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fduke3d.jsdos"
  },
  {
    "id": "dos-warcraft-2",
    "title": "Warcraft II: Tides of Darkness",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Strategy",
    "year": 1995,
    "developer": "Blizzard",
    "rating": 4.9,
    "featured": true,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Warcraft%20II%20-%20Tides%20of%20Darkness%20(1995).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    "description": "มหากาพย์สงครามวางแผนการรบแบบ Real-Time ระหว่างเผ่ามนุษย์ (Humans) และ ออร์ค (Orcs)",
    "controls": "เมาส์: ควบคุม ยูนิต และสร้างสิ่งปลูกสร้าง",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fwarcraft-2.jsdos"
  },
  {
    "id": "dos-red-alert",
    "title": "Command & Conquer: Red Alert",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Strategy",
    "year": 1996,
    "developer": "Westwood",
    "rating": 5.0,
    "featured": true,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x01.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    "description": "สงครามเย็นย้อนเวลา ไอน์สไตน์ย้อนอดีตลบฮิตเลอร์ เกิดสงครามฝ่ายพันธมิตร vs โซเวียต",
    "controls": "เมาส์: สั่งการสร้างฐานและรถถังแมมมอธ",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fred-alert.jsdos"
  },
  {
    "id": "dos-simcity-2000",
    "title": "SimCity 2000",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Strategy",
    "year": 1993,
    "developer": "Maxis",
    "rating": 4.9,
    "featured": false,
    "thumbnail": "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x18.jpg",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    "description": "สร้างเมืองในฝัน วางระบบไฟฟ้า ประปา รถไฟใต้ดิน และรับมือภัยพิบัติเอเลี่ยนบุก",
    "controls": "เมาส์: วางผังเมืองและบริหารงบประมาณ",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fsimcity-2000.jsdos"
  },
  {
    "id": "dos-wolfenstein-3d",
    "title": "Wolfenstein 3D",
    "platform": "dos",
    "platformName": "MS-DOS",
    "genre": "Shooter",
    "year": 1992,
    "developer": "id Software",
    "rating": 4.8,
    "featured": false,
    "thumbnail": "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Wolfenstein%203D%20(1992).png",
    "banner": "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    "description": "สายลับ B.J. Blazkowicz แหกคุกปราสาท Wolfenstein และปราบกองทัพนาซี",
    "controls": "ลูกศร: เดิน / หัน | Ctrl: ยิง | Space: เปิดประตู",
    "embedUrl": "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fwolf3d.jsdos"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RETRO_GAMES_DATABASE };
}
