/**
 * Retro Games Hub - Game Catalog Database
 * Supporting: MS-DOS, NES, SNES, GBA, SEGA Genesis, Arcade
 */

const RETRO_GAMES_DATABASE = [
  // --- MS-DOS GAMES ---
  {
    id: "dos-doom",
    title: "DOOM (1993)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Shooter",
    year: 1993,
    developer: "id Software",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x77.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    description: "เกมยิงมุมมองบุคคลที่หนึ่งระดับตำนาน บุกตะลุยฝูงปีศาจจากนรกบนดาวอังคาร",
    controls: "ลูกศร: เดิน / หัน | Ctrl: ยิง | Alt: สไลด์ข้าง | Space: เปิดประตู | 1-7: เปลี่ยนอาวุธ",
    bundleUrl: "https://cdn.dos.zone/custom/dos/doom.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-prince-of-persia",
    title: "Prince of Persia (1989)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1989,
    developer: "Brøderbund",
    rating: 4.8,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co205v.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4q.jpg",
    description: "การผจญภัยของเจ้าชายเปอร์เซียในคุกใต้ดิน ต้องช่วยเจ้าหญิงให้ได้ภายใน 60 นาที",
    controls: "ลูกศร ซ้าย-ขวา: วิ่ง | ลูกศร ขึ้น: กระโดด / ปีน | Shift: เดินย่อง / หยิบของ / ปัดดาบ",
    bundleUrl: "https://cdn.dos.zone/custom/dos/prince-of-persia.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-dangerous-dave",
    title: "Dangerous Dave in the Deserted Pirate's Hideout",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1988,
    developer: "John Romero",
    rating: 4.7,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co294m.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    description: "เกมเก็บถ้วยทองในตำนานห้องคอมโรงเรียน เก็บไอเทมและเจ็ทแพ็คเพื่อผ่านด่าน",
    controls: "ลูกศร: ซ้าย / ขวา | Space / ลูกศรขึ้น: กระโดด | Ctrl: ยิงปืน (เมื่อมีปืน)",
    bundleUrl: "https://cdn.dos.zone/custom/dos/dave.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-wolf3d",
    title: "Wolfenstein 3D (1992)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Shooter",
    year: 1992,
    developer: "id Software",
    rating: 4.7,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x76.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3v.jpg",
    description: "บิดาแห่งเกม FPS แหกค่ายกักกันปราสาทวูลเฟนสไตน์",
    controls: "ลูกศร: เดิน | Ctrl: ยิง | Space: เปิดประตู | 1-4: เลือกอาวุธ",
    bundleUrl: "https://cdn.dos.zone/custom/dos/wolf3d.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-aladdin",
    title: "Disney's Aladdin (DOS)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Action",
    year: 1994,
    developer: "Virgin Interactive",
    rating: 4.8,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1z54.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4a.jpg",
    description: "การผจญภัยของอะลาดินในเมืองอัคราบาห์ กราฟิกและเพลงประกอบสุดคลาสสิก",
    controls: "ลูกศร: เคลื่อนที่ | Ctrl: ฟันดาบ | Alt: กระโดด | Space: ปาแอปเปิ้ล",
    bundleUrl: "https://cdn.dos.zone/custom/dos/aladdin.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-lion-king",
    title: "The Lion King (DOS)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1994,
    developer: "Westwood Studios",
    rating: 4.6,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1z53.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4b.jpg",
    description: "พาซิมบ้าน้อยเติบโตเป็นเจ้าป่าเพื่อทวงบัลลังก์คืนจากสการ์",
    controls: "ลูกศร: ทิศทาง | Ctrl: ตะปบ/คำราม | Alt: กระโดด",
    bundleUrl: "https://cdn.dos.zone/custom/dos/lion-king.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-skyroads",
    title: "SkyRoads (1993)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Racing",
    year: 1993,
    developer: "Bluemoon Interactive",
    rating: 4.7,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co21z9.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    description: "ขับยานอวกาศกระโดดข้ามรางอุปสรรคในอวกาศ เพลงและจังหวะสุดมันส์",
    controls: "ลูกศร: เลี้ยว ซ้าย-ขวา / เร่งความเร็ว | Space: กระโดด",
    bundleUrl: "https://cdn.dos.zone/custom/dos/skyroads.jsdos",
    emulatorType: "jsdos"
  },
  {
    id: "dos-jazz-jackrabbit",
    title: "Jazz Jackrabbit (1994)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1994,
    developer: "Epic MegaGames",
    rating: 4.8,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co203t.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4k.jpg",
    description: "กระต่ายเขียวติดปืนซิ่งความเร็วสูง ต่อสู้กับกองทัพเต่าร้าย",
    controls: "ลูกศร: วิ่ง | Space: ยิง | Alt: กระโดด",
    bundleUrl: "https://cdn.dos.zone/custom/dos/jazz-jackrabbit.jsdos",
    emulatorType: "jsdos"
  },

  // --- NES / FAMICOM GAMES ---
  {
    id: "nes-super-mario-bros",
    title: "Super Mario Bros (1985)",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Platformer",
    year: 1985,
    developer: "Nintendo",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7d.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3u.jpg",
    description: "จุดเริ่มต้นของลุงหนวด มาริโอ้ ตะลุยอาณาจักรเห็ดช่วยเจ้าหญิงพีช",
    controls: "D-Pad / ลูกศร: เคลื่อนที่ | Z: ปุ่ม B (วิ่ง/ยิงไฟ) | X: ปุ่ม A (กระโดด) | Enter: Start",
    romUrl: "https://archive.org/download/SuperMarioBros.Nes/Super%20Mario%20Bros..nes",
    emulatorType: "emulatorjs",
    core: "nes"
  },
  {
    id: "nes-contra",
    title: "Contra (1988)",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Shooter",
    year: 1988,
    developer: "Konami",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y7m.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    description: "เกมยิงบู๊ล้างผลาญระดับตำนาน พร้อมสูตร 30 ตัว บน บน ล่าง ล่าง ซ้าย ขวา ซ้าย ขวา B A",
    controls: "ลูกศร: เล็ง/เดิน | Z: ปุ่ม B (ยิง) | X: ปุ่ม A (กระโดด) | Enter: Start",
    romUrl: "https://archive.org/download/Contra_1988_Konami/Contra.nes",
    emulatorType: "emulatorjs",
    core: "nes"
  },
  {
    id: "nes-rockman-2",
    title: "Mega Man 2 / Rockman 2",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Action",
    year: 1988,
    developer: "Capcom",
    rating: 4.9,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9a.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f41.jpg",
    description: "ภาคที่ได้รับการยกย่องว่าดีที่สุดของร็อคแมน กำจัด 8 บอสเพื่อชิงอาวุธ",
    controls: "ลูกศร: เดิน | Z: ยิงบัสเตอร์ | X: กระโดด | Enter: Start",
    romUrl: "https://archive.org/download/MegaMan2_1988_Capcom/Mega%20Man%202.nes",
    emulatorType: "emulatorjs",
    core: "nes"
  },
  {
    id: "nes-battle-city",
    title: "Battle City (รถถัง)",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Arcade",
    year: 1985,
    developer: "Namco",
    rating: 4.8,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2044.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    description: "ขับรถถังปกป้องฐานนกอินทรี และทำลายรถถังศัตรูให้หมดสิ้น",
    controls: "ลูกศร: บังคับทิศทาง | Z / X: ยิงกระสุนปืนใหญ่",
    romUrl: "https://archive.org/download/BattleCity_1985_Namco/Battle%20City.nes",
    emulatorType: "emulatorjs",
    core: "nes"
  },

  // --- SNES (SUPER NINTENDO) ---
  {
    id: "snes-super-mario-world",
    title: "Super Mario World (1990)",
    platform: "snes",
    platformName: "Super Nintendo",
    genre: "Platformer",
    year: 1990,
    developer: "Nintendo",
    rating: 5.0,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7e.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f43.jpg",
    description: "การผจญภัยบนเกาะไดโนเสาร์และเปิดตัวคู่หูขี่ได้อย่างเจ้ากิ้งก่า Yoshi",
    controls: "ลูกศร: เดิน | Z: B (กระโดด) | X: A (สปิน) | A: Y (วิ่ง/พ่นไฟ) | S: X",
    romUrl: "https://archive.org/download/SuperMarioWorld_SNES/Super%20Mario%20World.sfc",
    emulatorType: "emulatorjs",
    core: "snes"
  },
  {
    id: "snes-street-fighter-2-turbo",
    title: "Street Fighter II Turbo",
    platform: "snes",
    platformName: "Super Nintendo",
    genre: "Fighting",
    year: 1993,
    developer: "Capcom",
    rating: 4.9,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9q.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    description: "ฮาโดเคน! โชริวเคน! ศึกประลองหมัดสะท้านฟ้าความเร็วเทอร์โบ",
    controls: "ลูกศร: ทิศทาง | A,S,D: ต่อย เบา-กลาง-หนัก | Z,X,C: เตะ เบา-กลาง-หนัก",
    romUrl: "https://archive.org/download/StreetFighterIITurbo_SNES/Street%20Fighter%20II%20Turbo.sfc",
    emulatorType: "emulatorjs",
    core: "snes"
  },
  {
    id: "snes-chrono-trigger",
    title: "Chrono Trigger (1995)",
    platform: "snes",
    platformName: "Super Nintendo",
    genre: "RPG",
    year: 1995,
    developer: "Squaresoft",
    rating: 5.0,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9r.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "สุดยอดเกม JRPG ท่องกาลเวลา อภิมหาโปรเจกต์จากผู้สร้าง Dragon Quest และ Final Fantasy",
    controls: "ลูกศร: ทิศทาง | Z: ตกลง / สำรวจ | X: ยกเลิก / วิ่ง | A: เมนูคำสั่ง",
    romUrl: "https://archive.org/download/ChronoTrigger_SNES/Chrono%20Trigger.sfc",
    emulatorType: "emulatorjs",
    core: "snes"
  },

  // --- GAME BOY ADVANCE (GBA) ---
  {
    id: "gba-pokemon-emerald",
    title: "Pokemon Emerald Version",
    platform: "gba",
    platformName: "Game Boy Advance",
    genre: "RPG",
    year: 2004,
    developer: "Game Freak",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y57.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f46.jpg",
    description: "ภาคยอดนิยมตลอดกาลในดินแดน Hoenn หยุดยั้งศึกเทพ Rayquaza, Kyogre และ Groudon",
    controls: "ลูกศร: เดิน | Z: ปุ่ม A (ตกลง) | X: ปุ่ม B (ยกเลิก/วิ่ง) | A: ปุ่ม L | S: ปุ่ม R | Enter: Start | Shift: Select",
    romUrl: "https://archive.org/download/PokemonEmerald_GBA/Pokemon%20-%20Emerald%20Version%20%28USA%2C%20Europe%29.gba",
    emulatorType: "emulatorjs",
    core: "gba"
  },
  {
    id: "gba-zelda-minish-cap",
    title: "The Legend of Zelda: The Minish Cap",
    platform: "gba",
    platformName: "Game Boy Advance",
    genre: "Adventure",
    year: 2004,
    developer: "Capcom / Nintendo",
    rating: 4.9,
    featured: false,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x8u.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f47.jpg",
    description: "Link และหมวกเวทมนตร์ย่อส่วน สู่การผจญภัยในโลกจิ๋วสุดมหัศจรรย์",
    controls: "ลูกศร: เคลื่อนที่ | Z: ฟันดาบ (A) | X: ใช้อาวุธรอง (B) | A: กลิ้งตัว (R) | Enter: Start",
    romUrl: "https://archive.org/download/LegendOfZeldaTheMinishCap_GBA/Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20%28USA%29.gba",
    emulatorType: "emulatorjs",
    core: "gba"
  },

  // --- SEGA GENESIS / MEGA DRIVE ---
  {
    id: "sega-sonic-the-hedgehog-2",
    title: "Sonic The Hedgehog 2 (1992)",
    platform: "sega",
    platformName: "Sega Genesis",
    genre: "Platformer",
    year: 1992,
    developer: "Sega",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1x9w.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f49.jpg",
    description: "เจ้าเม่นสายฟ้าโซนิคและคู่หูเทลส์ วิ่งทะลุความเร็วเสียงปราบ ดร.เอ้กแมน",
    controls: "ลูกศร: ซ้าย/ขวา กลิ้ง/หมอบ | Z / X / C: กระโดด / Spin Dash",
    romUrl: "https://archive.org/download/SonicTheHedgehog2_Genesis/Sonic%20The%20Hedgehog%202%20%28World%29.md",
    emulatorType: "emulatorjs",
    core: "segaMD"
  },

  // --- ARCADE / MAME ---
  {
    id: "arcade-metal-slug",
    title: "Metal Slug - Super Vehicle-001",
    platform: "arcade",
    platformName: "Neo Geo / Arcade",
    genre: "Shooter",
    year: 1996,
    developer: "Nazca / SNK",
    rating: 4.9,
    featured: true,
    thumbnail: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1y3x.jpg",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f4a.jpg",
    description: "เกมอาร์เคดยิงแหลก 2D ระดับมาสเตอร์พีซ กราฟิกอนิเมชันพิกเซลสุดประณีต",
    controls: "ลูกศร: ทิศทาง | Z: ยิงปืน | X: กระโดด | C: ปาระเบิด | Space: หยอดเหรียญ (Insert Coin) | Enter: 1P Start",
    romUrl: "https://archive.org/download/MetalSlug_Arcade/mslug.zip",
    emulatorType: "emulatorjs",
    core: "neogeo"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { RETRO_GAMES_DATABASE };
}
