/**
 * PENNUENG GAME - 100% Working Web Player Catalog (Embedded Web Game Streams)
 * Supports: PS1, MS-DOS, NES, SNES, GBA, SEGA, Arcade
 */

const RETRO_GAMES_DATABASE = [
  // ==========================================
  // --- PLAYSTATION 1 (PS1 ALL-TIME LEGENDS) ---
  // ==========================================
  {
    id: "ps1-pepsiman",
    title: "Pepsiman (1999)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1999,
    developer: "KID",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Pepsiman%20(Japan).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    description: "เป๊ปซี่แมนฮีโร่วิ่งส่งเป๊ปซี่ระดับตำนาน หลบสิ่งกีดขวางและกระป๋องยักษ์ไล่หลัง",
    controls: "ลูกศร: ซ้าย/ขวา | Z: สไลด์ (X) | X: กระโดด (Square) | A: พุ่งชน (Circle) | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/41743-pepsiman.html"
  },
  {
    id: "ps1-harvest-moon-btn",
    title: "Harvest Moon: Back to Nature",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "RPG",
    year: 1999,
    developer: "Victor Interactive",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Harvest%20Moon%20-%20Back%20to%20Nature%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "เกมปลูกผัก เลี้ยงวัว จีบสาว ที่ครองใจเกมเมอร์ไทยมากที่สุดตลอดกาล",
    controls: "ลูกศร: เดิน | Z: หยิบ/คุย (X) | X: ใช้อุปกรณ์ (Square) | A: กิน/เก็บ (Triangle) | S: วิ่ง (R1) | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/41706-harvest-moon-back-to-nature.html"
  },
  {
    id: "ps1-crash-team-racing",
    title: "Crash Team Racing (CTR)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Racing",
    year: 1999,
    developer: "Naughty Dog",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Crash%20Team%20Racing%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    description: "ศึกแข่งรถโกคาร์ทดริฟท์พ่นไฟและยิงอาวุธสุดมันส์ของเจ้าหมา Crash Bandicoot",
    controls: "ลูกศร: เลี้ยว | Z: เร่งความเร็ว (X) | X: ยิงอาวุธ (Circle) | A/S: กระโดดดริฟท์ (L1/R1)",
    embedUrl: "https://www.retrogames.cc/embed/41675-crash-team-racing.html"
  },
  {
    id: "ps1-tekken-3",
    title: "Tekken 3 (1998)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Fighting",
    year: 1998,
    developer: "Namco",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Tekken%203%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    description: "สุดยอดเกมต่อสู้ 3D ในตำนาน หมัดเหล็ก Jin Kazama, Hwoarang, Eddy Gordo",
    controls: "ลูกศร: เคลื่อนที่ | A: ต่อยซ้าย | S: ต่อยขวา | Z: เตะซ้าย | X: เตะขวา | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/41724-tekken-3.html"
  },
  {
    id: "ps1-bloody-roar-2",
    title: "Bloody Roar II (แปลงร่างสัตว์)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Fighting",
    year: 1999,
    developer: "Eighting / Hudson",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Bloody%20Roar%20II%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    description: "ศึกต่อสู้แปลงร่างเป็นสัตว์ดุร้าย เสือโคร่ง หมาป่า ตุ่น สิงโต พร้อมท่าไม้ตายสัตว์ป่าสุดโหด",
    controls: "ลูกศร: ทิศทาง | A: ต่อย | Z: เตะ | X: ปุ่มแปลงร่างสัตว์ (Beast)",
    embedUrl: "https://www.retrogames.cc/embed/41668-bloody-roar-ii.html"
  },
  {
    id: "ps1-yugioh",
    title: "Yu-Gi-Oh! Forbidden Memories",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Strategy",
    year: 1999,
    developer: "Konami",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Yu-Gi-Oh!%20-%20Forbidden%20Memories%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "เกมการ์ดยูกิโออียิปต์โบราณ ผสมการ์ดมังกรทองตาคู่และตามหาไอเทมพันปี",
    controls: "ลูกศร: เลื่อนการ์ด | Z: วางการ์ด (X) | X: ผสมการ์ด (Square) | A: ดูรายละเอียด",
    embedUrl: "https://www.retrogames.cc/embed/41738-yu-gi-oh-forbidden-memories.html"
  },
  {
    id: "ps1-chocobo-racing",
    title: "Chocobo Racing (แข่งรถโจโคโบะ)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Racing",
    year: 1999,
    developer: "Squaresoft",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Chocobo%20Racing%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3t.jpg",
    description: "แข่งรถแฟนตาซี ดริฟท์เก็บลูกแก้วเวทมนตร์ ปล่อยคาถาไฟ สายฟ้า และบาฮามุท",
    controls: "ลูกศร: เลี้ยว | Z: เร่งความเร็ว | X: ใช้เวทมนตร์ | A: สกิลประจำตัว",
    embedUrl: "https://www.retrogames.cc/embed/41671-chocobo-racing.html"
  },
  {
    id: "ps1-dokapon",
    title: "Dokapon! - Ikari no Tekken (โดกาปอง)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "RPG",
    year: 1998,
    developer: "Asmik Ace",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Dokapon!%20-%20Ikari%20no%20Tekken%20(Japan).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "เกมกระดานมิตรภาพแตกหักในตำนาน ทอยลูกเต๋า เดินช่อง แย่งหมู่บ้าน ปราบเพื่อนสนิท",
    controls: "ลูกศร: เลือกคำสั่ง/ทิศทาง | Z: ตกลง (Circle) | X: ยกเลิก (X)",
    embedUrl: "https://www.retrogames.cc/embed/42602-dokapon-ikari-no-tekken.html"
  },
  {
    id: "ps1-digimon-world",
    title: "Digimon World (เลี้ยงดิจิมอน)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "RPG",
    year: 1999,
    developer: "Bandai",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Digimon%20World%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "พาคู่หูดิจิมอนฝึกฝน ให้อาหาร พาเข้าห้องน้ำ พัฒนาร่าง และฟื้นฟูเกาะ File Island",
    controls: "ลูกศร: เดิน | Z: สำรวจ/คุย | X: ยกเลิก | A: เมนูคำสั่ง",
    embedUrl: "https://www.retrogames.cc/embed/41680-digimon-world.html"
  },
  {
    id: "ps1-resident-evil-2",
    title: "Resident Evil 2 (DualShock)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1998,
    developer: "Capcom",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Resident%20Evil%202%20-%20Dual%20Shock%20Ver.%20(USA)%20(Disc%201).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    description: "หนีตายจากฝูงซอมบี้ในสถานีตำรวจเมืองแรคคูนซิตีกับ Leon S. Kennedy และ Claire Redfield",
    controls: "ลูกศร: หมุน/เดินหน้า | Z: ยิง/สำรวจ (X) | X: ยกเลิก/วิ่ง (Square) | A: ยกปืนเล็ง (R1)",
    embedUrl: "https://www.retrogames.cc/embed/41716-resident-evil-2-dual-shock-edition-disc-1.html"
  },
  {
    id: "ps1-resident-evil-3",
    title: "Resident Evil 3: Nemesis",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1999,
    developer: "Capcom",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Resident%20Evil%203%20-%20Nemesis%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    description: "Jill Valentine หนีการตามล่าอย่างไร้ความปรานีของอสูรชีวภาพ Nemesis 'STARS...'",
    controls: "ลูกศร: เคลื่อนที่ | Z: ยิง/สำรวจ | X: วิ่ง/หลบหลีก | A: เล็งปืน",
    embedUrl: "https://www.retrogames.cc/embed/41717-resident-evil-3-nemesis.html"
  },
  {
    id: "ps1-dino-crisis-2",
    title: "Dino Crisis 2 (ไดโนเสาร์)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 2000,
    developer: "Capcom",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Dino%20Crisis%202%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    description: "เกมยิงไดโนเสาร์สุดมันส์ เก็บแต้มคอมโบ อัปเกรดปืนลูกซองและปืนไฟ",
    controls: "ลูกศร: เดิน | Z: ยิงปืน | X: วิ่ง | A: ดาบฟัน",
    embedUrl: "https://www.retrogames.cc/embed/41682-dino-crisis-2.html"
  },
  {
    id: "ps1-castlevania-sotn",
    title: "Castlevania: Symphony of the Night",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1997,
    developer: "Konami",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Castlevania%20-%20Symphony%20of%20the%20Night%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "มาสเตอร์พีซแห่งปราสาทแดร็กคูล่า Alucard บุกปราสาทกลับหัว ระบบ RPG สมบูรณ์แบบ",
    controls: "ลูกศร: เดิน | Z: ฟันดาบ (Square) | X: กระโดด (X) | A: แปลงร่างค้างคาว/หมอก",
    embedUrl: "https://www.retrogames.cc/embed/41670-castlevania-symphony-of-the-night.html"
  },
  {
    id: "ps1-megaman-x4",
    title: "Mega Man X4 (Rockman X4)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1997,
    developer: "Capcom",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Mega%20Man%20X4%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f41.jpg",
    description: "เลือกเล่นเป็น X หรือดาบเซเบอร์ Zero เพลงประกอบและอนิเมะคัตซีนสุดมันส์",
    controls: "ลูกศร: ทิศทาง | Z: ชาร์จยิง/ฟันดาบ (Square) | X: กระโดด (X) | A: แดช (Circle)",
    embedUrl: "https://www.retrogames.cc/embed/41712-mega-man-x4.html"
  },
  {
    id: "ps1-final-fantasy-7",
    title: "Final Fantasy VII",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "RPG",
    year: 1997,
    developer: "Squaresoft",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Final%20Fantasy%20VII%20(USA)%20(Disc%201).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f45.jpg",
    description: "มหากาพย์ของ Cloud Strife และดาบยักษ์ Buster Sword ปะทะ Sephiroth",
    controls: "ลูกศร: เดิน | Z: สำรวจ/ตกลง (Circle) | X: ยกเลิก/วิ่ง (X) | A: เปิดเมนู (Triangle)",
    embedUrl: "https://www.retrogames.cc/embed/41687-final-fantasy-vii-disc-1.html"
  },
  {
    id: "ps1-metal-gear-solid",
    title: "Metal Gear Solid (Disc 1)",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Action",
    year: 1998,
    developer: "Konami",
    rating: 5.0,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Metal%20Gear%20Solid%20(USA)%20(Disc%201).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    description: "สุดยอดเกมสายลับ Solid Snake ลอบเร้นฐานเกาะ Shadow Moses",
    controls: "ลูกศร: ย่อง/หมอบ | Z: ต่อย/ยิง | X: หมอบคลาน | A: เรียกวิทยุ Codec",
    embedUrl: "https://www.retrogames.cc/embed/41713-metal-gear-solid-disc-1.html"
  },
  {
    id: "ps1-wwf-smackdown-2",
    title: "WWF SmackDown! 2: Know Your Role",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Fighting",
    year: 2000,
    developer: "Yuke's",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/WWF%20SmackDown!%202%20-%20Know%20Your%20Role%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    description: "เกมมวยปล้ำยุคทอง The Rock, Stone Cold, Triple H, Undertaker โดดทับโต๊ะและเก้าอี้สุดมันส์",
    controls: "ลูกศร: เคลื่อนที่ | Z: ต่อย (Square) | X: จับล็อก (Circle) | A: วิ่ง (Triangle) | S: ขึ้นเชือก",
    embedUrl: "https://www.retrogames.cc/embed/41737-wwf-smackdown-2-know-your-role.html"
  },
  {
    id: "ps1-crash-bandicoot-3",
    title: "Crash Bandicoot 3: Warped",
    platform: "ps1",
    platformName: "PlayStation 1",
    genre: "Platformer",
    year: 1998,
    developer: "Naughty Dog",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/Crash%20Bandicoot%20-%20Warped%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    description: "ท่องกาลเวลา ขี่เสือน้อยกำแพงเมืองจีน ขับเจ็ทสกี และปราบ ดร.คอร์เทกซ์",
    controls: "ลูกศร: เดิน | Z: กระโดด (X) | X: หมุนตัวสปิน (Square) | A: สไลด์/หมอบ",
    embedUrl: "https://www.retrogames.cc/embed/41674-crash-bandicoot-3-warped.html"
  },

  // ==========================================
  // --- MS-DOS GAMES (PC CLASSICS) ---
  // ==========================================
  {
    id: "dos-doom",
    title: "DOOM (1993)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Shooter",
    year: 1993,
    developer: "id Software",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Doom%20(1993).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f39.jpg",
    description: "เกมยิงมุมมองบุคคลที่หนึ่งระดับตำนาน บุกตะลุยฝูงปีศาจจากนรกบนดาวอังคาร",
    controls: "ลูกศร: เดิน / หัน | Ctrl: ยิง | Alt: สไลด์ข้าง | Space: เปิดประตู | 1-7: เปลี่ยนอาวุธ",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fdoom.jsdos"
  },
  {
    id: "dos-prince-of-persia",
    title: "Prince of Persia (1989)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1989,
    developer: "Brøderbund",
    rating: 4.8,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Prince%20of%20Persia%20(1990).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7g4q.jpg",
    description: "การผจญภัยของเจ้าชายเปอร์เซียในคุกใต้ดิน ต้องช่วยเจ้าหญิงให้ได้ภายใน 60 นาที",
    controls: "ลูกศร ซ้าย-ขวา: วิ่ง | ลูกศร ขึ้น: กระโดด / ปีน | Shift: เดินย่อง / หยิบของ / ปัดดาบ",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fprince-of-persia.jsdos"
  },
  {
    id: "dos-dangerous-dave",
    title: "Dangerous Dave",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Platformer",
    year: 1988,
    developer: "John Romero",
    rating: 4.7,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Dangerous%20Dave%20(1990).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    description: "เกมเก็บถ้วยทองในตำนานห้องคอมโรงเรียน เก็บไอเทมและเจ็ทแพ็คเพื่อผ่านด่าน",
    controls: "ลูกศร: ซ้าย / ขวา | Space / ลูกศรขึ้น: กระโดด | Ctrl: ยิงปืน",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fdave.jsdos"
  },
  {
    id: "dos-duke-nukem-3d",
    title: "Duke Nukem 3D (1996)",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Shooter",
    year: 1996,
    developer: "3D Realms",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Duke%20Nukem%203D%20(1996).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f48.jpg",
    description: "ฮีโร่กล้ามโต Duke Nukem บุกกวาดล้างเอเลี่ยนที่มายึดครองลอสแองเจลิส",
    controls: "ลูกศร / WASD: เคลื่อนที่ | Ctrl: ยิง | Space: เปิดประตู/สำรวจ | E: เตะ",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fduke3d.jsdos"
  },
  {
    id: "dos-warcraft-2",
    title: "Warcraft II: Tides of Darkness",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Strategy",
    year: 1995,
    developer: "Blizzard Entertainment",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Warcraft%20II%20-%20Tides%20of%20Darkness%20(1995).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    description: "มหากาพย์สงครามวางแผนการรบแบบ Real-Time ระหว่างเผ่ามนุษย์ (Humans) และ ออร์ค (Orcs)",
    controls: "เมาส์: ควบคุม ยูนิต และสร้างสิ่งปลูกสร้าง",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fwarcraft-2.jsdos"
  },
  {
    id: "dos-red-alert",
    title: "Command & Conquer: Red Alert",
    platform: "dos",
    platformName: "MS-DOS",
    genre: "Strategy",
    year: 1996,
    developer: "Westwood Studios",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/DOS/master/Named_Boxarts/Command%20%26%20Conquer%20-%20Red%20Alert%20(1996).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    description: "สงครามเย็นย้อนเวลา ไอน์สไตน์ย้อนอดีตลบฮิตเลอร์ เกิดสงครามฝ่ายพันธมิตร vs โซเวียต",
    controls: "เมาส์: สั่งการสร้างฐานและรถถังแมมมอธ",
    embedUrl: "https://dos.zone/player/?bundleUrl=https%3A%2F%2Fcdn.dos.zone%2Fcustom%2Fdos%2Fred-alert.jsdos"
  },

  // ==========================================
  // --- NES / FAMICOM (8-BIT CLASSICS) ---
  // ==========================================
  {
    id: "nes-super-mario-bros",
    title: "Super Mario Bros",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Platformer",
    year: 1985,
    developer: "Nintendo",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20Bros.%20(World).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f3u.jpg",
    description: "จุดเริ่มต้นของลุงหนวด มาริโอ้ ตะลุยอาณาจักรเห็ดช่วยเจ้าหญิงพีช",
    controls: "D-Pad / ลูกศร: เคลื่อนที่ | Z: ปุ่ม B (วิ่ง/ยิงไฟ) | X: ปุ่ม A (กระโดด) | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/16858-super-mario-bros.html"
  },
  {
    id: "nes-contra",
    title: "Contra (1988)",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Shooter",
    year: 1988,
    developer: "Konami",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Contra%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f40.jpg",
    description: "เกมยิงบู๊ล้างผลาญระดับตำนาน พร้อมสูตร 30 ตัว บน บน ล่าง ล่าง ซ้าย ขวา ซ้าย ขวา B A",
    controls: "ลูกศร: เล็ง/เดิน | Z: ปุ่ม B (ยิง) | X: ปุ่ม A (กระโดด) | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/16752-contra-usa.html"
  },
  {
    id: "nes-rockman-2",
    title: "Mega Man 2 / Rockman 2",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Action",
    year: 1988,
    developer: "Capcom",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Mega%20Man%202%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f41.jpg",
    description: "ภาคที่ได้รับการยกย่องว่าดีที่สุดของร็อคแมน กำจัด 8 บอสเพื่อชิงอาวุธ",
    controls: "ลูกศร: เดิน | Z: ยิงบัสเตอร์ | X: กระโดด | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/17066-mega-man-2-usa.html"
  },
  {
    id: "nes-battle-city",
    title: "Battle City (รถถัง)",
    platform: "nes",
    platformName: "NES / Famicom",
    genre: "Arcade",
    year: 1985,
    developer: "Namco",
    rating: 4.8,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Nintendo_Entertainment_System/master/Named_Boxarts/Battle%20City%20(Japan).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f42.jpg",
    description: "ขับรถถังปกป้องฐานนกอินทรี และทำลายรถถังศัตรูให้หมดสิ้น",
    controls: "ลูกศร: บังคับทิศทาง | Z / X: ยิงกระสุนปืนใหญ่",
    embedUrl: "https://www.retrogames.cc/embed/16694-battle-city-japan.html"
  },

  // ==========================================
  // --- SNES (SUPER NINTENDO 16-BIT) ---
  // ==========================================
  {
    id: "snes-super-mario-world",
    title: "Super Mario World (1990)",
    platform: "snes",
    platformName: "Super Nintendo",
    genre: "Platformer",
    year: 1990,
    developer: "Nintendo",
    rating: 5.0,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Super%20Mario%20World%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f43.jpg",
    description: "การผจญภัยบนเกาะไดโนเสาร์และเปิดตัวคู่หูขี่ได้อย่างเจ้ากิ้งก่า Yoshi",
    controls: "ลูกศร: เดิน | Z: B (กระโดด) | X: A (สปิน) | A: Y (วิ่ง/พ่นไฟ) | S: X",
    embedUrl: "https://www.retrogames.cc/embed/20703-super-mario-world-usa.html"
  },
  {
    id: "snes-street-fighter-2-turbo",
    title: "Street Fighter II Turbo",
    platform: "snes",
    platformName: "Super Nintendo",
    genre: "Fighting",
    year: 1993,
    developer: "Capcom",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Super_Nintendo_Entertainment_System/master/Named_Boxarts/Street%20Fighter%20II%20Turbo%20-%20Hyper%20Fighting%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f44.jpg",
    description: "ฮาโดเคน! โชริวเคน! ศึกประลองหมัดสะท้านฟ้าความเร็วเทอร์โบ",
    controls: "ลูกศร: ทิศทาง | A,S,D: ต่อย เบา-กลาง-หนัก | Z,X,C: เตะ เบา-กลาง-หนัก",
    embedUrl: "https://www.retrogames.cc/embed/20696-street-fighter-ii-turbo-usa.html"
  },

  // ==========================================
  // --- GAME BOY ADVANCE (GBA 32-BIT) ---
  // ==========================================
  {
    id: "gba-pokemon-emerald",
    title: "Pokemon Emerald Version",
    platform: "gba",
    platformName: "Game Boy Advance",
    genre: "RPG",
    year: 2004,
    developer: "Game Freak",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance/master/Named_Boxarts/Pokemon%20-%20Emerald%20Version%20(USA%2C%20Europe).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f46.jpg",
    description: "ภาคยอดนิยมตลอดกาลในดินแดน Hoenn หยุดยั้งศึกเทพ Rayquaza, Kyogre และ Groudon",
    controls: "ลูกศร: เดิน | Z: ปุ่ม A (ตกลง) | X: ปุ่ม B (ยกเลิก/วิ่ง) | A: ปุ่ม L | S: ปุ่ม R | Enter: Start | Shift: Select",
    embedUrl: "https://www.retrogames.cc/embed/26857-pokemon-emerald-version-u.html"
  },
  {
    id: "gba-zelda-minish-cap",
    title: "The Legend of Zelda: The Minish Cap",
    platform: "gba",
    platformName: "Game Boy Advance",
    genre: "Adventure",
    year: 2004,
    developer: "Capcom / Nintendo",
    rating: 4.9,
    featured: false,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance/master/Named_Boxarts/Legend%20of%20Zelda%2C%20The%20-%20The%20Minish%20Cap%20(USA).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f47.jpg",
    description: "Link และหมวกเวทมนตร์ย่อส่วน สู่การผจญภัยในโลกจิ๋วสุดมหัศจรรย์",
    controls: "ลูกศร: เคลื่อนที่ | Z: ฟันดาบ (A) | X: ใช้อาวุธรอง (B) | A: กลิ้งตัว (R) | Enter: Start",
    embedUrl: "https://www.retrogames.cc/embed/26522-the-legend-of-zelda-the-minish-cap-u.html"
  },

  // ==========================================
  // --- SEGA GENESIS / MEGA DRIVE ---
  // ==========================================
  {
    id: "sega-sonic-the-hedgehog-2",
    title: "Sonic The Hedgehog 2 (1992)",
    platform: "sega",
    platformName: "Sega Genesis",
    genre: "Platformer",
    year: 1992,
    developer: "Sega",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/Sega_-_Mega_Drive_-_Genesis/master/Named_Boxarts/Sonic%20The%20Hedgehog%202%20(World).png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f49.jpg",
    description: "เจ้าเม่นสายฟ้าโซนิคและคู่หูเทลส์ วิ่งทะลุความเร็วเสียงปราบ ดร.เอ้กแมน",
    controls: "ลูกศร: ซ้าย/ขวา กลิ้ง/หมอบ | Z / X / C: กระโดด / Spin Dash",
    embedUrl: "https://www.retrogames.cc/embed/22906-sonic-the-hedgehog-2-world.html"
  },

  // ==========================================
  // --- ARCADE / NEO GEO (COIN-OP) ---
  // ==========================================
  {
    id: "arcade-metal-slug",
    title: "Metal Slug - Super Vehicle-001",
    platform: "arcade",
    platformName: "Neo Geo / Arcade",
    genre: "Shooter",
    year: 1996,
    developer: "Nazca / SNK",
    rating: 4.9,
    featured: true,
    thumbnail: "https://raw.githubusercontent.com/libretro-thumbnails/SNK_-_Neo_Geo/master/Named_Boxarts/Metal%20Slug%20-%20Super%20Vehicle-001.png",
    banner: "https://images.igdb.com/igdb/image/upload/t_1080p/sc7f4a.jpg",
    description: "เกมอาร์เคดยิงแหลก 2D ระดับมาสเตอร์พีซ กราฟิกอนิเมชันพิกเซลสุดประณีต",
    controls: "ลูกศร: ทิศทาง | Z: ยิงปืน | X: กระโดด | C: ปาระเบิด | Space: หยอดเหรียญ (Insert Coin) | Enter: 1P Start",
    embedUrl: "https://www.retrogames.cc/embed/10041-metal-slug-super-vehicle-001.html"
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { RETRO_GAMES_DATABASE };
}
